# =============================================================
# Docker DBサーバーの接続
# =============================================================
spring:
  datasource:
    url: jdbc:mysql://DB:3300/sampleDB
    username: root
    password: root  
# =============================================================
# Mybatis
# =============================================================
mybatis:
  mapper-locations:
  - classpath*:/mapper/*.xml
# =============================================================
# Logging
# =============================================================
logging:
  level:
    com:
      example: debug