# ===============================================================
# DB接続
# ===============================================================
spring:
  datasource:
    url: jdbc:mysql://db/sampleDB
    username: root
    password: root