# ================================================================================================================
# 仮想サーバー構築
# ================================================================================================================
version: '3.9'
services:
  # ================================================================================================================
  # client server
  # ================================================================================================================
  client:
    image: node:18
    volumes:
      - ./client:/client
    tty: true
    depends_on:
      - api
    networks:
      # ネットワークの指定
      - CRUD_network # ネットワーク指定
  # ================================================================================================================
  # api server
  # ================================================================================================================
  api:
    container_name: applcation_server
    image: eclipse-temurin:18
    volumes:
      - ./api:/api
    ports:
      - 8000:8080
    tty: true
    depends_on:
      - db
    networks:
      # ネットワークの指定
      - CRUD_network # ネットワーク指定
  # ================================================================================================================
  # database server
  # ================================================================================================================
  db:
    container_name: db_server # サーバー名指定
    image: mysql:8.0.29 # サーバーのイメージ指定
    # サーバーとの共有
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d # dbの情報
    tty: true
    environment:
      - MYSQL_DATABASE=sampleDB # Databaseの設定
      - MYSQL_ROOT_PASSWORD=root # mysqlログインパスワードをrootに設定
      - TZ=Asia/Tokyo # 時間を東京に設定
    ports:
      - 3300:3306 # portをローカルの3300に設定
    networks:
      # ネットワークの指定
      - CRUD_network # ネットワーク指定
# ================================================================================================================
# network
# ================================================================================================================
networks:
  CRUD_network:
    driver: bridge # ドライバー指定
