# ================================================================================================================
# 仮想サーバー構築
# ================================================================================================================
version: '3.9'
services:
  # ================================================================================================================
  # app server
  # ================================================================================================================
  app:
    container_name: app_server
    image: eclipse-temurin:18
    volumes:
      - ./app:/app
    ports:
      - 8000:8080
    tty: true
    networks:
      - CRUD_network
  # ================================================================================================================
  # database server
  # ================================================================================================================
  db:
    container_name: db_server # サーバー名指定
    image: mysql:8.0.29 # サーバーのイメージ指定
    # サーバーとの共有
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d # dbの情報
    tty: true
    environment:
      - MYSQL_DATABASE=sampleDB # Databaseの設定
      - MYSQL_ROOT_PASSWORD=root # mysqlログインパスワードをrootに設定
      - TZ=Asia/Tokyo # 時間を東京に設定
    ports:
      - 3300:3306 # portをローカルの3300に設定
    networks:
      # ネットワークの指定
      - CRUD_network # ネットワーク指定
# ================================================================================================================
# network
# ================================================================================================================
networks:
  CRUD_network:
    driver: bridge # ドライバー指定