# =========================================================
# mysqlの接続[localhost]
# =========================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3300/sampleDB
    username: root
    password: root
# =========================================================