# =============================================================
# DB接続
# =============================================================
# local環境接続
# =============================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3300/sampleDB
    username: root
    password: root
# =============================================================
# Docker環境
# =============================================================
---
spring:
  datasource:
    url: jdbc:mysql://172.19.0.2:3300/sampleDB
    username: root
    password: root
# =============================================================
# mybatis 設定
# =============================================================
---
mybatis:
  mapper-locations:
  - classpath*:/mapper/mysql/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.domain.user.model
    